CREATE DATABASE appdb;
GO
USE appdb;
GO


CREATE TABLE dbo.customers(
  id INT IDENTITY PRIMARY KEY,
  name NVARCHAR(100) NOT NULL,
  email NVARCHAR(200) NOT NULL UNIQUE,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);


CREATE TABLE dbo.orders(
  id INT IDENTITY PRIMARY KEY,
  customer_id INT NOT NULL REFERENCES dbo.customers(id),
  total_amount DECIMAL(18,2) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
