-- Generated 2025-12-09T08:59:54.672174Z

CREATE TABLE IF NOT EXISTS public.customers (
  "ID" INTEGER NOT NULL,
  "FULL_NAME" TEXT NOT NULL,
  "EMAIL" TEXT NOT NULL,
  "CREATED_AT" TIMESTAMPTZ NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public.orders (
  "ID" INTEGER NOT NULL,
  "CUSTOMER_ID" INTEGER NOT NULL,
  "TOTAL_AMOUNT" DOUBLE PRECISION NOT NULL,
  "CREATED_AT" TIMESTAMPTZ NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public.heartbeat (
  "ID" INTEGER NOT NULL,
  id INTEGER NOT NULL,
  ts_utc BIGINT NOT NULL,
  PRIMARY KEY ("ID")
);
