-- Generated 2025-12-09T17:43:27.729214Z

CREATE TABLE IF NOT EXISTS public.customers (
  "ID" INTEGER NOT NULL,
  "FULL_NAME" TEXT NOT NULL,
  "EMAIL" TEXT NOT NULL,
  "CREATED_AT" TIMESTAMPTZ NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public.orders (
  "ID" INTEGER NOT NULL,
  "CUSTOMER_ID" INTEGER NOT NULL,
  "TOTAL_AMOUNT" DOUBLE PRECISION NOT NULL,
  "CREATED_AT" TIMESTAMPTZ NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public.heartbeat (
  "ID" INTEGER NOT NULL,
  id INTEGER NOT NULL,
  ts_utc BIGINT NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public.updt_basics (
  "ID" INTEGER NOT NULL,
  "UPDATE_NUMBER" INTEGER NOT NULL,
  "TITLE" TEXT NOT NULL,
  "ENGINE_PHASE" TEXT NOT NULL,
  "USER_ID" INTEGER NOT NULL,
  "SPEC_CHANGE_ID" INTEGER NOT NULL,
  "CREATE_DATE" TEXT NOT NULL,
  "RELEASED" BOOLEAN NOT NULL,
  "IS_SUBMITTED" BOOLEAN NOT NULL,
  "IS_RETURNED" BOOLEAN NOT NULL,
  "IS_COPY" BOOLEAN NOT NULL,
  "IS_ERP_ADMIN" BOOLEAN NOT NULL,
  "IS_SYSPRO_IN_PROCESS" BOOLEAN NOT NULL,
  "IS_SYSPRO_COMPLETE" BOOLEAN NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public.update_specifics1 (
  "ID" INTEGER NOT NULL,
  "UPDATE_ID" INTEGER NOT NULL,
  "UPDATE_NUMBER" INTEGER NOT NULL,
  "NEW_PART_NUMBER" TEXT NOT NULL,
  "OLD_PART_NUMBER" TEXT NOT NULL,
  "STATUS" TEXT NOT NULL,
  "DUE_DATE" TEXT NOT NULL,
  "VENDOR" TEXT NOT NULL,
  "VENDOR_PART_NUMBER" TEXT NOT NULL,
  "ITEM_NUMBER" INTEGER NOT NULL,
  "NEW_COST" DOUBLE PRECISION NOT NULL,
  "OBSOLETE_COST" DOUBLE PRECISION NOT NULL,
  "IS_EBOM" BOOLEAN NOT NULL,
  "IS_ENTERED_ERP" BOOLEAN NOT NULL,
  "IS_MILEAGE_TRACKED" BOOLEAN NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public.user_update_approvers (
  "ID" INTEGER NOT NULL,
  "USER_ID" INTEGER NOT NULL,
  "APPROVAL_CODE" TEXT NOT NULL,
  "ROUTING_ID" INTEGER NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public.updt_join_updates_routings (
  "ID" INTEGER NOT NULL,
  "UPDATE_ID" INTEGER NOT NULL,
  "ROUTING_ID" INTEGER NOT NULL,
  "ROUTING_ORDER" INTEGER NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public.updt_return_to_author (
  "ID" INTEGER NOT NULL,
  "UPDATE_ID" INTEGER NOT NULL,
  "RETURN_DT" TEXT NOT NULL,
  "RETURN_TEXT" TEXT NOT NULL,
  "RETURN_USER_ID" INTEGER NOT NULL,
  "LOG_ID" INTEGER NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public.bom_master (
  "ID" INTEGER NOT NULL,
  "USER_ID" INTEGER NOT NULL,
  "UPDATE_ID" INTEGER NOT NULL,
  "LINEITEM_NUMBER" INTEGER NOT NULL,
  "CREATE_DT" TEXT NOT NULL,
  "MODIFY_DT" TEXT NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public.bom_operationtypes (
  "ID" INTEGER NOT NULL,
  "NAME" TEXT NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public.bom_operations (
  "ID" INTEGER NOT NULL,
  "BOM_ID" INTEGER NOT NULL,
  "OPTYPE_ID" INTEGER NOT NULL,
  "OPTYPE_NAME" TEXT NOT NULL,
  "WORKCENTER" TEXT NOT NULL,
  "SETUP_TIME" DOUBLE PRECISION NOT NULL,
  "LEAD_TIME" DOUBLE PRECISION NOT NULL,
  "QTY_PER" DOUBLE PRECISION NOT NULL,
  "UOM" TEXT NOT NULL,
  "ROUTE" INTEGER NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public.bom_childpartnumbers (
  "ID" INTEGER NOT NULL,
  "BOM_ID" INTEGER NOT NULL,
  "CHILD_PARTNUMBER" TEXT NOT NULL,
  "QTY" DOUBLE PRECISION NOT NULL,
  "ORDER_BY" INTEGER NOT NULL,
  "ROUTE" INTEGER NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public.data_kits (
  "ID" INTEGER NOT NULL,
  "KIT_NAME" TEXT NOT NULL,
  "KIT_DESC" TEXT NOT NULL,
  "IS_DELETED" BOOLEAN NOT NULL,
  "PHASE_NUMBER" TEXT NOT NULL,
  "IS_BOM" BOOLEAN NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public.updt_join_updatespageitems (
  "ID" INTEGER NOT NULL,
  "UPDATE_ID" INTEGER NOT NULL,
  "LINEITEM_NUMBER" INTEGER NOT NULL,
  "SPECIFIC_ID" INTEGER NOT NULL,
  "PAGE_NUMBER" TEXT NOT NULL,
  "ITEM_NUMBER" INTEGER NOT NULL,
  "ENGINE_SPEC" TEXT NOT NULL,
  "QTY" DOUBLE PRECISION NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public.updt_join_updateskits (
  "ID" INTEGER NOT NULL,
  "UPDATE_ID" INTEGER NOT NULL,
  "SPECIFIC_ID" INTEGER NOT NULL,
  "LINEITEM_NUMBER" INTEGER NOT NULL,
  "KIT_NAME" TEXT NOT NULL,
  "KIT_ACTION" TEXT NOT NULL,
  "IS_NEWPARTACTION" BOOLEAN NOT NULL,
  "IS_OLDPARTACTION" BOOLEAN NOT NULL,
  "STRUCT_ON" TEXT NOT NULL,
  "STRUCT_OFF" TEXT NOT NULL,
  "QTY" DOUBLE PRECISION NOT NULL,
  "EBOM_ID" INTEGER NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public.ebom_062104 (
  "ID" INTEGER NOT NULL,
  "UPDATE_ID" INTEGER NOT NULL,
  "SPECIFIC_ID" INTEGER NOT NULL,
  "LINEITEM_NUMBER" INTEGER NOT NULL,
  "ENGINE_SPEC" TEXT NOT NULL,
  "CURRENT_PART" TEXT NOT NULL,
  "DESCRIPTION" TEXT NOT NULL,
  "QTY" TEXT NOT NULL,
  "NEW_QTY_ACTION" TEXT NOT NULL,
  "OLD_PART_NO" TEXT NOT NULL,
  "KIT_NAME" TEXT NOT NULL,
  "DATE_ADDED" TEXT NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public.log_ebomhistory (
  "ID" INTEGER NOT NULL,
  "EBOM_ID" INTEGER NOT NULL,
  "UPDATE_ID" INTEGER NOT NULL,
  "SPECIFIC_ID" INTEGER NOT NULL,
  "LINEITEM_NUMBER" INTEGER NOT NULL,
  "ENGINE_SPEC" TEXT NOT NULL,
  "CURRENT_PART" TEXT NOT NULL,
  "DESCRIPTION" TEXT NOT NULL,
  "QTY" TEXT NOT NULL,
  "NEW_QTY_ACTION" TEXT NOT NULL,
  "OLD_PART_NO" TEXT NOT NULL,
  "KIT_NAME" TEXT NOT NULL,
  "LOG_DT" TEXT NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public.updt_join_updatesebom (
  "ID" INTEGER NOT NULL,
  "EBOM_ID" INTEGER NOT NULL,
  "UPDATE_ID" INTEGER NOT NULL,
  "SPECIFIC_ID" INTEGER NOT NULL,
  "IS_NEWPARTACTION" BOOLEAN NOT NULL,
  "IS_OLDPARTACTION" BOOLEAN NOT NULL,
  "LINEITEM_NUMBER" INTEGER NOT NULL,
  "OBS_CC" TEXT NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public.user_master (
  "ID" INTEGER NOT NULL,
  "USER_LOGIN" TEXT NOT NULL,
  "FIRST_NAME" TEXT NOT NULL,
  "LAST_NAME" TEXT NOT NULL,
  "EMAIL" TEXT NOT NULL,
  "CREATED_DT" TEXT NOT NULL,
  "IS_DELETED" BOOLEAN NOT NULL,
  "IS_ONHOLD" BOOLEAN NOT NULL,
  PRIMARY KEY ("ID")
);
